In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
from sklearn.preprocessing import MinMaxScaler
from sklearn import datasets
from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.model_selection import GridSearchCV

In [2]:
df_train = pd.read_csv("training_data.csv")
df_train

,county,cases,deaths,date_index_converted,county_data_length,core_jaccard,core_cosine,core_intersection,social_jaccard,politics_jaccard,...,labor_force_rate,unemployment_rate,median_housing_cost,median_household_earnings,median_worker_earnings,percent_insured,percent_married,poverty_rate,median_property_value,percent_white
0,Richland,0,0,day_10,363,0.000000,0.000000,0.000000,0.000011,0.000151,...,55.5,7.5,675,41877,23210,90.5,48.3,15.6,103700,0.868085
1,Lawrence,119,0,day_105,256,0.000000,0.000000,0.000000,0.000000,0.000000,...,53.5,6.5,655,42874,23510,92.2,49.3,18.6,101500,0.954027
2,Wayne,49,0,day_90,769,0.000076,0.000370,0.006502,0.000039,0.000000,...,64.0,4.0,762,50383,26658,87.2,55.1,13.0,140100,0.950541
3,Fayette,7,0,day_85,36,0.000000,0.000000,0.000000,0.000000,0.000000,...,59.3,6.3,732,40503,25858,91.3,51.8,17.7,108900,0.940054
4,Trumbull,0,0,day_7,554,0.000000,0.000000,0.000000,0.000046,0.000000,...,56.4,5.9,661,43073,25800,91.7,49.1,17.2,101600,0.885724
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3136,Summit,105,0,day_81,6121,0.000094,0.000491,0.008169,0.000041,0.000011,...,64.2,6.4,859,50765,28345,93.2,47.3,13.6,137000,0.791435
3137,Fayette,0,0,day_55,28,0.000000,0.000000,0.000000,0.000000,0.000000,...,59.3,6.3,732,40503,25858,91.3,51.8,17.7,108900,0.940054
3138,Clark,147,0,day_106,929,0.000013,0.000105,0.001076,0.000009,0.000012,...,60.6,7.7,736,43625,25300,92.7,48.1,16.6,107300,0.865754
3139,Logan,0,0,day_1,144,0.000000,0.000000,0.000000,0.000000,0.000000,...,62.5,5.8,766,49783,28346,90.7,55.2,13.7,127200,0.949363
3140,Paulding,0,0,day_60,16,0.000000,0.000000,0.000000,0.000000,0.000000,...,61.5,5.0,660,45550,25476,93.0,57.3,10.7,92500,0.949607

In [3]:
df_test = pd.read_csv("test_data.csv")
df_test

,index,county,deaths,date_index_converted,county_data_length,core_jaccard,core_cosine,core_intersection,social_jaccard,politics_jaccard,...,labor_force_rate,unemployment_rate,median_housing_cost,median_household_earnings,median_worker_earnings,percent_insured,percent_married,poverty_rate,median_property_value,percent_white
0,0,Carroll,0,day_22,40,0.000000,0.000000,0.000000,0.000106,0.000000,...,58.2,4.7,713,47075,26589,88.5,56.9,14.8,116700,0.974052
1,1,Richland,3,day_118,17,0.000661,0.002567,0.058824,0.000494,0.000000,...,55.5,7.5,675,41877,23210,90.5,48.3,15.6,103700,0.868085
2,2,Portage,0,day_51,1210,0.000000,0.000000,0.000000,0.000013,0.000009,...,65.5,7.2,896,52552,25904,93.5,46.0,14.5,152000,0.909878
3,3,Auglaize,0,day_27,38,0.000000,0.000000,0.000000,0.000000,0.000000,...,67.0,3.4,758,54274,30438,95.7,59.4,9.0,143100,0.970007
4,4,Montgomery,0,day_8,4328,0.000005,0.000036,0.000462,0.000043,0.000033,...,61.8,8.0,830,43829,26292,92.0,44.8,17.9,112100,0.731997
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7326,7326,Meigs,0,day_51,24,0.000000,0.000000,0.000000,0.000000,0.000473,...,52.8,10.4,571,37813,21714,91.7,51.9,22.5,87400,0.974262
7327,7327,Knox,3,day_109,128,0.000000,0.000000,0.000000,0.000033,0.000000,...,62.3,5.8,784,48533,24568,89.9,51.7,13.8,138900,0.965641
7328,7328,Columbiana,0,day_37,194,0.000000,0.000000,0.000000,0.000043,0.000000,...,58.0,7.5,656,44497,23781,91.3,52.0,15.4,104300,0.949782
7329,7329,Ashtabula,21,day_114,139,0.000000,0.000000,0.000000,0.000000,0.000000,...,54.7,7.4,695,40544,23117,90.0,47.9,19.8,106300,0.929083
7330,7330,Clark,0,day_68,287,0.000000,0.000000,0.000000,0.000000,0.000079,...,60.6,7.7,736,43625,25300,92.7,48.1,16.6,107300,0.865754

In [4]:
X_train = pd.concat([df_train.iloc[:,2], df_train.iloc[:, 4:]], axis=1)
Y_train = df_train.iloc[:,1].values
X_train

,deaths,county_data_length,core_jaccard,core_cosine,core_intersection,social_jaccard,politics_jaccard,politics_democratic_love_jaccard,nationalistic_jaccard,politics_republican_hate_jaccard,...,labor_force_rate,unemployment_rate,median_housing_cost,median_household_earnings,median_worker_earnings,percent_insured,percent_married,poverty_rate,median_property_value,percent_white
0,0,363,0.000000,0.000000,0.000000,0.000011,0.000151,0.000053,0.0,0.00000,...,55.5,7.5,675,41877,23210,90.5,48.3,15.6,103700,0.868085
1,0,256,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.00000,...,53.5,6.5,655,42874,23510,92.2,49.3,18.6,101500,0.954027
2,0,769,0.000076,0.000370,0.006502,0.000039,0.000000,0.000000,0.0,0.00000,...,64.0,4.0,762,50383,26658,87.2,55.1,13.0,140100,0.950541
3,0,36,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.00000,...,59.3,6.3,732,40503,25858,91.3,51.8,17.7,108900,0.940054
4,0,554,0.000000,0.000000,0.000000,0.000046,0.000000,0.000000,0.0,0.00000,...,56.4,5.9,661,43073,25800,91.7,49.1,17.2,101600,0.885724
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3136,0,6121,0.000094,0.000491,0.008169,0.000041,0.000011,0.000003,0.0,0.00001,...,64.2,6.4,859,50765,28345,93.2,47.3,13.6,137000,0.791435
3137,0,28,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.00000,...,59.3,6.3,732,40503,25858,91.3,51.8,17.7,108900,0.940054
3138,0,929,0.000013,0.000105,0.001076,0.000009,0.000012,0.000000,0.0,0.00000,...,60.6,7.7,736,43625,25300,92.7,48.1,16.6,107300,0.865754
3139,0,144,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.00000,...,62.5,5.8,766,49783,28346,90.7,55.2,13.7,127200,0.949363
3140,0,16,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.00000,...,61.5,5.0,660,45550,25476,93.0,57.3,10.7,92500,0.949607

In [5]:
Y_train

array([  0, 119,  49, ..., 147,   0,   0])

In [6]:
X_test = pd.concat([df_test.iloc[:,2], df_test.iloc[:, 4:]], axis=1)
X_test

,deaths,county_data_length,core_jaccard,core_cosine,core_intersection,social_jaccard,politics_jaccard,politics_democratic_love_jaccard,nationalistic_jaccard,politics_republican_hate_jaccard,...,labor_force_rate,unemployment_rate,median_housing_cost,median_household_earnings,median_worker_earnings,percent_insured,percent_married,poverty_rate,median_property_value,percent_white
0,0,40,0.000000,0.000000,0.000000,0.000106,0.000000,0.000000,0.000000,0.00000,...,58.2,4.7,713,47075,26589,88.5,56.9,14.8,116700,0.974052
1,3,17,0.000661,0.002567,0.058824,0.000494,0.000000,0.000000,0.000000,0.00000,...,55.5,7.5,675,41877,23210,90.5,48.3,15.6,103700,0.868085
2,0,1210,0.000000,0.000000,0.000000,0.000013,0.000009,0.000036,0.000000,0.00000,...,65.5,7.2,896,52552,25904,93.5,46.0,14.5,152000,0.909878
3,0,38,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,...,67.0,3.4,758,54274,30438,95.7,59.4,9.0,143100,0.970007
4,0,4328,0.000005,0.000036,0.000462,0.000043,0.000033,0.000015,0.000014,0.00002,...,61.8,8.0,830,43829,26292,92.0,44.8,17.9,112100,0.731997
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7326,0,24,0.000000,0.000000,0.000000,0.000000,0.000473,0.000000,0.000000,0.00000,...,52.8,10.4,571,37813,21714,91.7,51.9,22.5,87400,0.974262
7327,3,128,0.000000,0.000000,0.000000,0.000033,0.000000,0.000000,0.000000,0.00000,...,62.3,5.8,784,48533,24568,89.9,51.7,13.8,138900,0.965641
7328,0,194,0.000000,0.000000,0.000000,0.000043,0.000000,0.000000,0.000000,0.00000,...,58.0,7.5,656,44497,23781,91.3,52.0,15.4,104300,0.949782
7329,21,139,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,...,54.7,7.4,695,40544,23117,90.0,47.9,19.8,106300,0.929083
7330,0,287,0.000000,0.000000,0.000000,0.000000,0.000079,0.000226,0.000000,0.00000,...,60.6,7.7,736,43625,25300,92.7,48.1,16.6,107300,0.865754

In [7]:
selector = SelectKBest(score_func=f_regression, k=10)
X_train_selected = selector.fit_transform(X_train, Y_train)
X_test_selected = selector.transform(X_test)

In [8]:
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}
model = RandomForestRegressor(random_state=35)
grid_search = GridSearchCV(model, param_grid, cv=5, n_jobs=1)
grid_search.fit(X_train_selected, Y_train)
best_model = grid_search.best_estimator_
Y_pred = best_model.predict(X_test_selected)
Y_pred

array([ 81.41 , 390.495,   0.   , ...,   0.   , 541.52 ,   0.98 ])

In [9]:
Y_pred = pd.DataFrame(Y_pred, columns= ['cases'])

In [10]:
Y_pred

        cases
0      81.410
1     390.495
2       0.000
3       0.735
4       0.000
...       ...
7326    0.035
7327   85.365
7328    0.000
7329  541.520
7330    0.980

[7331 rows x 1 columns]

In [11]:
#read the sample_submission file
sample_submission = pd.read_csv('sample_submission.csv')
sample_submission.head()

   Index  Cases
0      0   81.0
1      1  195.0
2      2    0.0
3      3    4.0
4      4    0.0

In [14]:
#replace Cases values with the test_df_new['cases'] values
sample_submission['Cases'] = Y_pred
sample_submission['Cases'] = sample_submission['Cases'].round(0)
sample_submission['Cases'] = sample_submission['Cases'].mask(sample_submission['Cases'] < 0, 0)
sample_submission.head()

   Index  Cases
0      0   81.0
1      1  390.0
2      2    0.0
3      3    1.0
4      4    0.0

In [15]:
sample_submission.to_csv('submission_cases.csv', index=False)